# setup_env.ps1
# Windows PowerShell interactive .env generator
# Usage: Right click -> Run with PowerShell, or run: powershell -ExecutionPolicy Bypass -File .\setup_env.ps1

$ErrorActionPreference = "Stop"

function Ask-WithDefault {
    param(
        [string]$Prompt,
        [string]$DefaultValue
    )
    if ([string]::IsNullOrWhiteSpace($DefaultValue)) {
        $value = Read-Host $Prompt
    } else {
        $value = Read-Host "$Prompt [$DefaultValue]"
        if ([string]::IsNullOrWhiteSpace($value)) {
            $value = $DefaultValue
        }
    }
    return $value
}

function Ask-Required {
    param([string]$Prompt)
    do {
        $value = Read-Host $Prompt
        if ([string]::IsNullOrWhiteSpace($value)) {
            Write-Host "This value is required. Please enter it again." -ForegroundColor Yellow
        }
    } while ([string]::IsNullOrWhiteSpace($value))
    return $value
}

Write-Host "=========================================="
Write-Host " .env configuration generator"
Write-Host "=========================================="
Write-Host "1. Proxy / OpenAI-compatible provider"
Write-Host "2. Official OpenAI + Anthropic"
Write-Host ""

$mode = ""
do {
    $mode = Read-Host "Choose config mode, enter 1 or 2"
} while ($mode -ne "1" -and $mode -ne "2")

$envPath = Join-Path $PSScriptRoot ".env"

if (Test-Path $envPath) {
    $overwrite = Read-Host ".env already exists. Enter y to overwrite, anything else to cancel"
    if ($overwrite.ToLower() -ne "y") {
        Write-Host "Cancelled."
        exit 0
    }
}

if ($mode -eq "1") {
    Write-Host ""
    Write-Host "Selected: proxy configuration"

    $proxyBase = Ask-WithDefault "Enter proxy OpenAI API Base" "https://4router.net/v1"
    $proxyKey = Ask-Required "Enter proxy OpenAI API Key"

    $sameClaude = Read-Host "Use the same proxy base and key for Anthropic/Claude? Enter y for yes, anything else for separate config"
    if ($sameClaude.ToLower() -eq "y") {
        $proxyAnthropicBase = $proxyBase
        $proxyAnthropicKey = $proxyKey
    } else {
        $proxyAnthropicBase = Ask-WithDefault "Enter proxy Anthropic Base URL" "https://4router.net"
        $proxyAnthropicKey = Ask-Required "Enter proxy Anthropic API Key"
    }

    $modelAnalysis = Ask-WithDefault "Enter MODEL_ANALYSIS" "gpt-5.5"
    $modelCoderApi = Ask-WithDefault "Enter MODEL_CODER_API for reproduction agent LLM" "gpt-5.4-mini"
    $modelManagerSummary = Ask-WithDefault "Enter MODEL_MANAGER_SUMMARY" "gpt-5.4-mini"
    $modelDataProcess = Ask-WithDefault "Enter MODEL_DATA_PROCESS" "claude-opus-4-6"
    $coderExecutionMode = Ask-WithDefault "Enter CODER_EXECUTION_MODE: API / CLI_CODEX / CLI_CLAUDE" "API"

    $content = @"
# ==========================================
# 4Router / proxy API configuration
# Generated by setup_env.ps1
# ==========================================

# --- OpenAI-compatible models (GPT & Codex) ---
OPENAI_API_KEY=$proxyKey
OPENAI_API_BASE=$proxyBase
MODEL_ANALYSIS=$modelAnalysis
MODEL_CODER_API=$modelCoderApi
MODEL_MANAGER_SUMMARY=$modelManagerSummary
CODER_EXECUTION_MODE=$coderExecutionMode

# --- Anthropic models (Claude) ---
ANTHROPIC_API_KEY=$proxyAnthropicKey
ANTHROPIC_BASE_URL=$proxyAnthropicBase
MODEL_DATA_PROCESS=$modelDataProcess
"@
} else {
    Write-Host ""
    Write-Host "Selected: official OpenAI + Anthropic configuration"

    $openaiKey = Ask-Required "Enter OpenAI API Key"
    $openaiBase = Ask-WithDefault "Enter OpenAI API Base; leave empty for official direct" ""
    $anthropicKey = Ask-Required "Enter Anthropic API Key"
    $anthropicBase = Ask-WithDefault "Enter Anthropic Base URL; leave empty for official direct" ""

    $modelAnalysis = Ask-WithDefault "Enter MODEL_ANALYSIS" "gpt-5.5"
    $modelCoderApi = Ask-WithDefault "Enter MODEL_CODER_API for reproduction agent LLM" "gpt-5.4-mini"
    $modelManagerSummary = Ask-WithDefault "Enter MODEL_MANAGER_SUMMARY" "gpt-5.4-mini"
    $modelDataProcess = Ask-WithDefault "Enter MODEL_DATA_PROCESS" "claude-opus-4-6"
    $coderExecutionMode = Ask-WithDefault "Enter CODER_EXECUTION_MODE: API / CLI_CODEX / CLI_CLAUDE" "API"

    $content = @"
# ==========================================
# Official direct API configuration
# Generated by setup_env.ps1
# ==========================================
OPENAI_API_KEY=$openaiKey
OPENAI_API_BASE=$openaiBase
MODEL_ANALYSIS=$modelAnalysis
MODEL_CODER_API=$modelCoderApi
MODEL_MANAGER_SUMMARY=$modelManagerSummary
CODER_EXECUTION_MODE=$coderExecutionMode

ANTHROPIC_API_KEY=$anthropicKey
ANTHROPIC_BASE_URL=$anthropicBase
MODEL_DATA_PROCESS=$modelDataProcess
"@
}

Set-Content -Path $envPath -Value $content -Encoding UTF8

Write-Host ""
Write-Host "Generated .env file: $envPath" -ForegroundColor Green
Write-Host "Do not upload .env to GitHub."
