#!/usr/bin/env bash
set -euo pipefail

# Interactive .env generator for macOS / Linux
# Supports:
#   1) Proxy / OpenAI-compatible providers, with separate GPT/OpenAI and Claude/Anthropic keys/base URLs
#   2) Official direct OpenAI + Anthropic configuration

ENV_FILE=".env"
DEFAULT_OPENROUTER_BASE="https://openrouter.ai/api/v1"

ask() {
  local prompt="$1"
  local default_value="${2:-}"
  local answer=""

  if [[ -n "$default_value" ]]; then
    read -r -p "$prompt [$default_value]: " answer
    if [[ -z "$answer" ]]; then
      answer="$default_value"
    fi
  else
    read -r -p "$prompt: " answer
  fi

  printf '%s' "$answer"
}

ask_secret() {
  local prompt="$1"
  local answer=""
  read -r -s -p "$prompt: " answer
  echo
  printf '%s' "$answer"
}

write_env() {
  local mode="$1"
  local openai_base="$2"
  local openai_key="$3"
  local anthropic_base="$4"
  local anthropic_key="$5"
  local model_analysis="$6"
  local model_coder_api="$7"
  local model_manager_summary="$8"
  local model_data_process="$9"
  local coder_execution_mode="${10}"

  cat > "$ENV_FILE" <<EOT
# Generated by setup_env.sh
# Mode: $mode

# --- GPT / OpenAI-compatible configuration ---
OPENAI_API_KEY=$openai_key
OPENAI_API_BASE=$openai_base
MODEL_ANALYSIS=$model_analysis
MODEL_CODER_API=$model_coder_api
MODEL_MANAGER_SUMMARY=$model_manager_summary
CODER_EXECUTION_MODE=$coder_execution_mode

# --- Claude / Anthropic configuration ---
ANTHROPIC_API_KEY=$anthropic_key
ANTHROPIC_BASE_URL=$anthropic_base
MODEL_DATA_PROCESS=$model_data_process
EOT
}

clear || true

echo "========================================"
echo "  .env configuration generator"
echo "========================================"
echo
echo "请选择配置方式："
echo "1 = 中转站 / Proxy"
echo "2 = GPT / Claude 官方直连"
echo

choice=""
while [[ "$choice" != "1" && "$choice" != "2" ]]; do
  read -r -p "请输入 1 或 2: " choice
done

if [[ -f "$ENV_FILE" ]]; then
  echo
  read -r -p ".env 已存在，是否覆盖？输入 y 覆盖，其他任意键取消: " overwrite
  if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
    echo "已取消，没有修改 .env。"
    exit 0
  fi
fi

echo

if [[ "$choice" == "1" ]]; then
  mode="proxy"

  openai_base=$(ask "请输入 GPT/OpenAI 中转站 API Base" "$DEFAULT_OPENROUTER_BASE")
  openai_key=$(ask_secret "请输入 GPT/OpenAI 中转站 API Key")

  echo
  read -r -p "Claude/Anthropic 是否使用和 GPT/OpenAI 相同的中转站地址与 Key？[y/N]: " same_claude

  if [[ "$same_claude" =~ ^[Yy]$ ]]; then
    anthropic_base="$openai_base"
    anthropic_key="$openai_key"
  else
    anthropic_base=$(ask "请输入 Claude/Anthropic 中转站 Base URL" "$DEFAULT_OPENROUTER_BASE")
    anthropic_key=$(ask_secret "请输入 Claude/Anthropic 中转站 API Key")
  fi

else
  mode="official-direct"

  openai_key=$(ask_secret "请输入 OpenAI API Key")
  openai_base=$(ask "请输入 OpenAI API Base，官方直连可直接回车留空" "")

  anthropic_key=$(ask_secret "请输入 Anthropic/Claude API Key")
  anthropic_base=$(ask "请输入 Anthropic Base URL，官方直连可直接回车留空" "")
fi

echo
model_analysis=$(ask "请输入分析 Agent 使用的模型 MODEL_ANALYSIS" "gpt-5.5")
model_coder_api=$(ask "请输入代码 Agent API 模式使用的模型 MODEL_CODER_API" "gpt-5.4-mini")
model_manager_summary=$(ask "请输入管理/总结 Agent 使用的模型 MODEL_MANAGER_SUMMARY" "gpt-5.4-mini")
model_data_process=$(ask "请输入数据处理 Agent 使用的模型 MODEL_DATA_PROCESS" "claude-opus-4-6")
coder_execution_mode=$(ask "请输入代码 Agent 执行模式 CODER_EXECUTION_MODE，可选 API / CLI_CODEX / CLI_CLAUDE" "API")

write_env \
  "$mode" \
  "$openai_base" \
  "$openai_key" \
  "$anthropic_base" \
  "$anthropic_key" \
  "$model_analysis" \
  "$model_coder_api" \
  "$model_manager_summary" \
  "$model_data_process" \
  "$coder_execution_mode"

echo
echo "已生成 $ENV_FILE。"
echo "注意：不要把 .env 上传到 GitHub。建议在 .gitignore 中加入：.env"
